name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        # Gets tags for versioning information
        fetch-depth: 0
        # Get AvxWindowFmIndex submodule
        submodules: recursive
    # Fix ownership of the checkout dir
    - name: Set ownership
      run: |
        chown -R $(id -u):$(id -g) $PWD
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools build
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade cibuildwheel
    - name: Build AvxWindowFmIndex libraries
      run: |
       ./build_libraries.sh
    - name: Build wheel(s)
      run: |
        python -m cibuildwheel --output-dir dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
